articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'
urlpatterns = [
    path('<str:article_id>/read/', views.ArticleView.as_view(), name='article'),
]

langsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('articles/', include('articles.urls')),
    path('quiz/', include('quiz.urls')),
    path('admin/', admin.site.urls),
]

quiz/urls.py
from django.urls import path

from . import views

app_name = 'quiz'
urlpatterns = [
    path('random/', views.quiz, name='random_question'),
]

articles/models.py
from django.db import models

# Create your models here.

# a hap-dash conception of "topics"
class Topic(models.Model):
    name = models.CharField(max_length=64)
    index = models.IntegerField(default=-1)

    # this allows us to ref the object itself in a template to get it's name
    def __str__(self):
        return self.name

    # this is just here so I didn't have to refactor the template
    def subtopics(self):
        return self.subtopic_set.all()

class Subtopic(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=64)
    text = models.TextField(default = "<p>ERROR: TEXT MISSING</p>")
    index = models.IntegerField(default = -1)

    # this allows us to ref the object itself in a template to get it's name
    def __str__(self):
        return self.name

quiz/models.py
from django.db import models
from random import randint

# a question in the quiz
class Question(models.Model):
    prompt = models.TextField(default = "ERROR: QUESTION MISSING")

    def __str__(self):
        return self.prompt


# an answer to a question in the quiz
class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    value = models.TextField(default = "ERROR: ANSWER TEXT MISSING")
    correct = models.BooleanField()

    def __str__(self):
        return self.value

quiz/forms.py
from django import forms

class QuizForm(forms.Form):

    def __init__(self, question, *args, **kwargs):
        #question = kwargs.pop('question')
        super().__init__(*args, **kwargs)

        # get the answers to the given question
        answers = question.answer_set.all()
        # format the answers for the form
        # choices = zip(range(len(answers)), answers)
        choices = tuple( (x.id, x) for x in answers )

        self.fields['answer'] = forms.ChoiceField(label="Select your answer", choices=choices, widget=forms.RadioSelect)

articles/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from django.core import exceptions

from .models import *

# the actual view 
class ArticleView(TemplateView):

    template_name = "articles/article.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            context['article_id'] = Topic.objects.get(name=kwargs['article_id'])
        except exceptions.ObjectDoesNotExist:
            # non-existant articles can be handled gracefully by the template
            context['article_id'] = None
        context['topics'] = Topic.objects.all()
        return context

quiz/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from .forms import QuizForm
from .models import Question
from .models import Answer
from articles.models import Topic

from random import randint
from django.db.models.aggregates import Count

# Create your views here.

# view a quiz question
def quiz(request):
    
    context = dict()

    # rand int
    # code thanks to https://stackoverflow.com/questions/962619/how-to-pull-a-random-record-using-djangos-orm
    count = Question.objects.aggregate(count=Count('id'))['count']
    random_index = randint(0, count - 1)
    question = Question.objects.all()[random_index]

    if request.method == 'POST':
        # handle answer questions
        context['prev_answer'] = Answer.objects.get(id = request.POST.get('answer'))
    
    context['form'] = QuizForm(question)
    context['question'] = question
    context['topics'] = Topic.objects.all() # TODO: this feels like tentacles; and also redundent code

    return render(request, "quiz/quiz.html", context=context)

articles/templates/articles/article.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'articles/style.css' %}"/>
 
{% if topics %}
    {% include "articles/sidebar.html" %}
{% else %}
<div>
{% endif %}

<div class="pagecontent">

<!-- the website Header -->
<div class="top">
    <h1>Bilingual Education in America</h1>
    <h3>Site by team Tokyodachi</h3>
</div>

{% if article_id %}
<!-- THE ARTICLE PROPPER -->
<div class="article">


    <h1> {{ article_id }} </h1>
    <!-- some things to hyper-link to-->
    {% for subtopic in article_id.subtopics %}
        <div id="{{ subtopic }}">
            <h3>{{ subtopic|safe }}</h3>

            <p>
            {{ subtopic.text|safe }}
            </p>
        </div>
    {% endfor %}
{% else %}
    <p> Sorry, that's sound like an interesting topic,
        but we didn't have time to research it.
    </p>
</div>
{% endif %}

</div>

</div>

articles/templates/articles/quiz.html
{% load static %}

<form action="{% url 'quiz' %} method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Answer"/>
</form>

articles/templates/articles/sidebar.html
{% load static %}

<!-- SIDEBAR of TOPICS -->
<link rel="stylesheet" type="text/css" href="{% static 'articles/sidebar.css' %}"/>
<script type="text/javascript" src="{% static 'articles/collapsible.js' %}"></script>

<div class="sidebar">
    <ol>
    {% for topic in topics %}
        <li class="topic" onmouseover="temp_expand_id('subtopic_{{ topic }}')" onmouseout="end_temp_expand_id('subtopic_{{ topic }}')">
            <div class="sb_collapse_top">
                <a href="{% url 'articles:article' topic %}">{{ topic }}</a>
                <button class="sb_collapse" onclick="toggle_collapse_id('subtopic_{{ topic }}')">V</button>
            </div>
            <ol class="subtopics" id="subtopic_{{ topic }}">
                <!-- list each topic's subtopics -->
                {% for subtopic in topic.subtopics %}
                    <li class="subtopic">
                        <a href="{% url 'articles:article' topic %}#{{ subtopic }}">
                            {{ subtopic|safe }}
                        </a>
                    </li>
                {% endfor %}
            </ol>
            <!-- run this line of code to start collapsed -->
            <script type="text/javascript">toggle_collapse_id('subtopic_{{ topic }}');</script>
        </li>
    {% endfor %}
    </ol>
    <!-- TODO: put an expand-all button here~ish -->
    <a href="{% url 'quiz:random_question' %}">
        <img src="{% static 'articles/images/button_quiz.png' %}"/>
    </a>
</div>

<!-- Use class rideside if have a sidebar
    else us a generic div to contain the rest of the content -->
<div class="rightside">
<!-- YES, THIS LEAVES THIS DIV OPEN; PLEASE CLOSE IT-->

quiz/templates/quiz/quiz.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'quiz/style.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'articles/style.css' %}"/> <!-- TENTACLES!! -->

{%if topics %}
    {% include "articles/sidebar.html" %}
{% else %}
    <div>
{% endif %}

<div class="pagecontent">
<div class="top">
    <h1>Quiz!</h1>
</div>
<div class="article">
<div class="quizContainer">
<!-- the answer to the previous question -->
{% if prev_answer %}
    {% if prev_answer.correct %}
    <div class="quiz right">
        <p> "{{ prev_answer }}" was the correct answer! </p>
    {% else %}
    <div class="quiz wrong">
        <p> Sorry, "{{ prev_answer }}" wasn't the correct answer. </p>
    {% endif %}
    <!-- TODO: link to more information about the topic -->
    </div>
{% endif %}

<!-- the next question -->
<div class="quiz">
    <h2>Question:</h2>
    <span> {{ question }} <br/></span><br/>
    <form action="{% url 'quiz:random_question' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Answer"/>
    </form>
</div>
</div>
</div>
</div>


</div> <!-- close the div from sidebar -->